# Generated by Django 4.2.19 on 2026-02-09 10:31

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KonfigurasiServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_git_remote', models.CharField(default='origin', help_text='Format: ssh://user@ip_public_anda:port/path/ke/repo (Contoh: ssh://adi@103.10.10.10:22/c/laragon/www/websman11)', max_length=255)),
                ('ssh_public_key', models.TextField(blank=True, help_text="Salin key ini dan masukkan ke file 'authorized_keys' di komputer lokal Anda.")),
            ],
            options={
                'verbose_name_plural': 'Konfigurasi Server',
                'db_table': 'sekolah_konfigurasiserver',
            },
        ),
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(default='SMA Y8199 Tasikmalaya', max_length=100)),
                ('slogan', models.CharField(blank=True, default='Mewujudkan generasi cerdas, berkarakter, dan kompetitif.', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pengaturan/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='pengaturan/')),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('copyright', models.CharField(default='© 2026 Copyright SMA Y8199.', max_length=100)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pengaturan Website',
                'db_table': 'sekolah_pengaturan',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('subjudul', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar', models.ImageField(upload_to='sliders/')),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tampilan slide (angka kecil lebih dulu)')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Slider',
                'db_table': 'sekolah_slider',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='UpdateAplikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('versi', models.CharField(blank=True, help_text='Versi atau commit ID', max_length=50)),
                ('status', models.CharField(choices=[('Sukses', 'Sukses'), ('Gagal', 'Gagal')], default='Sukses', max_length=20)),
                ('log', models.TextField(blank=True, help_text='Log output dari proses update')),
            ],
            options={
                'verbose_name_plural': 'Update Aplikasi',
                'db_table': 'sekolah_updateaplikasi',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('url', models.CharField(help_text="Link tujuan (bisa '/profil/' atau 'https://...')", max_length=200)),
                ('aktif', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Jika ini adalah submenu, pilih menu utamanya', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='pengaturan.menu')),
            ],
            options={
                'verbose_name_plural': 'Menu Navigasi',
                'db_table': 'sekolah_menu',
            },
        ),
    ]
