# Generated by Django 4.2.19 on 2026-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('file_backup', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('status', models.CharField(choices=[('Sukses', 'Sukses'), ('Gagal', 'Gagal')], default='Sukses', max_length=20)),
                ('log', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Backup Database ke GitHub',
                'db_table': 'sekolah_backupdatabase',
            },
        ),
        migrations.AlterModelOptions(
            name='konfigurasiserver',
            options={'verbose_name_plural': 'Konfigurasi GitHub'},
        ),
        migrations.AlterModelOptions(
            name='updateaplikasi',
            options={'verbose_name_plural': 'Sinkronisasi ke GitHub'},
        ),
        migrations.AddField(
            model_name='konfigurasiserver',
            name='mysqldump_path',
            field=models.CharField(default='C:\\laragon82\\bin\\mysql\\mysql-8.4.3-winx64\\bin\\mysqldump.exe', help_text='Path lengkap ke file mysqldump.exe', max_length=255),
        ),
        migrations.AlterField(
            model_name='konfigurasiserver',
            name='ssh_public_key',
            field=models.TextField(blank=True, help_text='Opsional: SSH Public Key jika menggunakan SSH.'),
        ),
        migrations.AlterField(
            model_name='konfigurasiserver',
            name='url_git_remote',
            field=models.CharField(default='origin', help_text='URL Repository GitHub (Contoh: https://github.com/username/repo.git)', max_length=255),
        ),
        migrations.AlterField(
            model_name='updateaplikasi',
            name='log',
            field=models.TextField(blank=True, help_text='Log output dari proses sinkronisasi'),
        ),
    ]
