# Generated by Django 4.2.19 on 2026-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('subjudul', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar', models.ImageField(upload_to='sliders/')),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tampilan slide (angka kecil lebih dulu)')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Slider',
                'ordering': ['urutan'],
            },
        ),
    ]
