# Generated by Django 4.2.19 on 2026-02-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(default='SMA Y8199 Tasikmalaya', max_length=100)),
                ('slogan', models.CharField(blank=True, default='Mewujudkan generasi cerdas, berkarakter, dan kompetitif.', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pengaturan/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='pengaturan/')),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('copyright', models.CharField(default='© 2026 Copyright SMA Y8199.', max_length=100)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pengaturan Website',
            },
        ),
    ]
