# Generated by Django 4.2.19 on 2026-02-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_pengaturan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name_plural': 'Galeri (Album)'},
        ),
        migrations.AlterField(
            model_name='galeri',
            name='gambar',
            field=models.ImageField(help_text='Sampul Album Utama', upload_to='galeri/'),
        ),
        migrations.CreateModel(
            name='FotoGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='galeri/detail/')),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('galeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_foto', to='sekolah.galeri')),
            ],
            options={
                'verbose_name_plural': 'Foto Tambahan',
            },
        ),
    ]
