# Generated by Django 4.2.19 on 2026-02-09 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_alter_galeri_options_alter_galeri_gambar_fotogaleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('url', models.CharField(help_text="Link tujuan (bisa '/profil/' atau 'https://...')", max_length=200)),
                ('urutan', models.IntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Jika ini adalah submenu, pilih menu utamanya', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='sekolah.menu')),
            ],
            options={
                'verbose_name_plural': 'Menu Navigasi',
                'ordering': ['urutan'],
            },
        ),
    ]
