# Generated by Django 4.2.19 on 2026-02-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0005_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('konten', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='halaman/')),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Halaman Statis',
            },
        ),
    ]
