# Generated by Django 4.2.19 on 2026-02-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_halaman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Halaman',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
