# Generated by Django 4.2.19 on 2026-02-09 04:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_delete_halaman_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('url', models.CharField(help_text="Link tujuan (bisa '/profil/' atau 'https://...')", max_length=200)),
                ('aktif', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Jika ini adalah submenu, pilih menu utamanya', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='sekolah.menu')),
            ],
            options={
                'verbose_name_plural': 'Menu Navigasi',
            },
        ),
    ]
