# Generated by Django 4.2.19 on 2026-02-09 08:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0009_halaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halaman',
            name='konten',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
