# Generated by Django 4.2.19 on 2026-02-09 08:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0010_alter_halaman_konten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halaman',
            name='konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
