# Generated by Django 4.2.19 on 2026-02-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0011_alter_halaman_konten'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateAplikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('versi', models.CharField(blank=True, help_text='Versi atau commit ID', max_length=50)),
                ('status', models.CharField(choices=[('Sukses', 'Sukses'), ('Gagal', 'Gagal')], default='Sukses', max_length=20)),
                ('log', models.TextField(blank=True, help_text='Log output dari proses update')),
            ],
            options={
                'verbose_name_plural': 'Update Aplikasi',
            },
        ),
    ]
