# Generated by Django 4.2.19 on 2026-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0012_updateaplikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonfigurasiServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_git_remote', models.CharField(default='origin', help_text='Format: ssh://user@ip_public_anda:port/path/ke/repo (Contoh: ssh://adi@103.10.10.10:22/c/laragon/www/websman11)', max_length=255)),
                ('ssh_public_key', models.TextField(blank=True, help_text="Salin key ini dan masukkan ke file 'authorized_keys' di komputer lokal Anda.")),
            ],
            options={
                'verbose_name_plural': 'Konfigurasi Server',
            },
        ),
    ]
