# Generated by Django 4.2.19 on 2026-02-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0013_konfigurasiserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='fotogaleri',
            name='galeri',
        ),
        migrations.DeleteModel(
            name='KonfigurasiServer',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Pengaturan',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='UpdateAplikasi',
        ),
        migrations.DeleteModel(
            name='Berita',
        ),
        migrations.DeleteModel(
            name='FotoGaleri',
        ),
        migrations.DeleteModel(
            name='Galeri',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
