# Generated by Django 4.2.19 on 2026-02-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
                'db_table': 'sekolah_kategori',
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('konten', models.TextField()),
                ('penulis', models.CharField(max_length=100)),
                ('tanggal_publikasi', models.DateTimeField(auto_now_add=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='berita.kategori')),
            ],
            options={
                'verbose_name_plural': 'Berita',
                'db_table': 'sekolah_berita',
            },
        ),
    ]
