# Generated by Django 4.2.19 on 2026-02-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('gambar', models.ImageField(help_text='Sampul Album Utama', upload_to='galeri/')),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Galeri (Album)',
                'db_table': 'sekolah_galeri',
            },
        ),
        migrations.CreateModel(
            name='FotoGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='galeri/detail/')),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('galeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_foto', to='galeri.galeri')),
            ],
            options={
                'verbose_name_plural': 'Foto Tambahan',
                'db_table': 'sekolah_fotogaleri',
            },
        ),
    ]
